swagger: "2.0"
info:
  version: 1.0.0
  title: musicApp
  description: This is Music app for api
basePath: /api/v1
tags:
  - name: Users
    description: Users CRUD operations

consumes:
  - application/json
produces:
  - application/json


definitions:
  
  UsersBody:
    type: object
    title: users
    required:
      - email
      - firstName
      - lastName
    properties:
      email:
        type: string
        example: example@gmail.com
      firstName:
        type: string
        example: test
      lastName:
        type: string
        example: test

paths:
  

  /users:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new example
      parameters:
        - name: email
        - name: firstName
        - name: lastName
          in: body
          description: an users
          required: true
          schema:
            $ref: "#/definitions/UsersBody"
      responses:
        200:
          description: Returns all users

  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          type: string
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found
    delete:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to delete
          type: string
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found


