swagger: "2.0"
info:
  version: 1.0.0
  title: musicApp
  description: This is Music app for api
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  # - name: Specification
  #   description: The swagger API specification
  - name: Users
    description: Users CRUD operations

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  UsersBody:
    type: object
    title: users
    required:
      - name
    properties:
      name:
        type: string
        example: Pooja

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /users:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new example
      parameters:
        - name: user
          in: body
          description: an users
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all users

  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          type: integer
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found
    delete:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to delete
          type: integer
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found

  # /spec:
  #   get:
  #     tags:
  #       - Specification
  #     responses:
  #       200:
  #         description: Return the API specification
