swagger: "2.0"
info:
  version: 1.0.0
  title: musicApp
  description: Basic music app and apis
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Users
    description: The swagger API Users  

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
    UsersBody:
    type: object
    title: user
    required:
      - name
    properties:
      name:
        type: string
        example: hello    

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  /users:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new user
      parameters:
        - name: example
          in: body
          description: an user
          required: true
          schema: 
            $ref: "#/definitions/UsersBody"
      responses:
        200:
          description: Returns all users        